name: rdkit_colab
channels:
- rdkit
- conda-forge
dependencies:
- rdkit
- numpy
- ipython
- jupyter
- matplotlib
- numpy
- pandas
- cudatoolkit
- scipy
- seaborn
- tqdm
- scikit-learn
- cudnn
- tensorflow
- umap-learn
- mordred
- pip:
  - selfies
