name: rdkit_colab
channels:
- rdkit
- conda-forge
- conda install -c rdkit -c mordred-descriptor mordred
dependencies:
- rdkit
- numpy
- ipython
- jupyter
- matplotlib
- numpy
- pandas
- cudatoolkit
- scipy
- seaborn
- tqdm
- scikit-learn
- cudnn
- tensorflow
- umap-learn
- pip:
  - selfies
